### PR TITLE
Added button to copy seed

### PR DESCRIPTION
**Pull request by Mina928**
This PR works on implementing one of the features in issue #62 

This issue suggests methods to save and copy seeds, to make it easier for player to replay the same version of the game again. This PR added a new button next to the random seed button, which upon being clicked saves the seed to the user's clipboard, allowing them to easily paste it somewhere else for future use.  

The new button needed different sprites, so two new sprites were created, then packaged using the GDX Texture Packer. The newly packages files replaced the old ones.  Currently the random seed button and copy seed button have the same sprites, as trying to get unique sprites was leading to issues.

### CODE REVIEW

**Comment by Sesu8642** [comment]
I managed to fix the buttons having the same image and iterated on the icons a bit. I think it now works as you intended. :smiley: 

There are two changes I would like to have before merging. Let me know whether you want to work more on that or I should do it.

1. User feedback. Displaying the tick is a good idea but on touch devices it cannot really be seen cause the finger is on the button. I think the pressed button should have a "pressed" version of the copy icon. One idea to give better feedback would be to change the icon to the tick icon for maybe one second after the button was released and then change it back to the copy icon. This would give users a better chance to see the tick. But it's also a bit annoying to implement. Maybe you have better ideas.
2. The width of the other inputs above the seed row should be increased to match the new seed row width.

**Comment by Mina928** [comment]
Wow nice thanks for the help. Yes these are good suggestions, I can start looking into making those changes.

**Comment by Mina928** [comment]
Hey so sorry for the lack responsiveness recently.  I have gotten very busy and am not sure when I will have time to work on this again. Thanks so much for the experience and assistance, it was fun. Wish you luck!

**Comment by Sesu8642** [comment]
No worries. I will finish this. Thanks for your help! :)

**Comment by Sesu8642** [comment]
Thanks!

**Pull request merged**
