### PR TITLE
Updated enum and selection for map size

### PR DESCRIPTION
**Pull request by teeks99**
I'm very unsure about this commit, I can't figure out how to build so can't
test anything. There may be something else here that I'm missing, but I
think it is just order dependent.

### CODE REVIEW

**Comment by teeks99** [comment]
Any tips on how I can build this? I'm *not* a Java nor Gradle expert. 

I've heard great things about doing development in containers, and have a decent deal of experience with containers. If you have some build pointers I could try to setup a container that could do builds?

**Comment by Sesu8642** [comment]
Thanks for your contribution!

Here is some documentation from libGDX: https://libgdx.com/wiki/start/setup
I should setup a dev environment on a fresh OS and document it in the readme. Building and running the desktop version should be relatively straight forward. You need to have a JDK installed and run
`./gradlew desktop:run`

Important note: I want to preserve the option to build a release that contains unfree components. Some examples are to integrate with Google services for multiplayer or to use some payment APIs. Because of that, contributions to source code would need to be dual-licensed under GPL-3.0-or-later and something permissive like MIT. GitHub seems to have some mechanism for that but I need to look into it first.
Of course, the F-Droid version will stay completely free and it is up to you if dual-licensing is acceptable.

**Comment by Sesu8642** [comment]
GitHub Actions sounds like a good idea. I realized only now that is available for free in a limited capacity.

**Comment by teeks99** [comment]
Hmm, that command failed for me, looking for some android deps....even when targeting the desktop.

```
~/src/FeudalTactics$ ./gradlew desktop:run

Welcome to Gradle 6.5.1!

Here are the highlights of this release:
 - Experimental file-system watching
 - Improved version ordering
 - New samples

For more details see https://docs.gradle.org/6.5.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':android'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/home/tomkent/src/FeudalTactics/local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
```

**Comment by teeks99** [comment]
I'm fine with a dual license GPL-3 + MIT....but then why keep the GPL-3, if it is dual licensed the GPL-3 doesn't make any extra promises. Anyone wanting to take it can just take it under MIT. 

Either way you dice it, doesn't matter to me. I see this as a fun side project.

**Comment by teeks99** [comment]
Github actions are completely free (not even limited) for open source projects :-)  It's a great resource (at least until the business model changes).

**Comment by Sesu8642** [comment]
I added build instructions to the readme. Please let me know if they work for you.

**Comment by Sesu8642** [comment]
> I'm fine with a dual license GPL-3 + MIT....but then why keep the GPL-3, if it is dual licensed the GPL-3 doesn't make any extra promises. Anyone wanting to take it can just take it under MIT.
> 
> Either way you dice it, doesn't matter to me. I see this as a fun side project.

Right. The contributions can be just MIT.

**Comment by teeks99** [comment]
I was able to run a game on XXLarge size, it ran well...for the first time ever I actually saw the other players make their moves. Hope you have a big monitor if you want to play it.

**Comment by Sesu8642** [comment]
@teeks99 could you please sign the CLA by adding the date and your name to the table? Since you are the first one to sign it, please use the following format:

```
| Date | Name |
| - | - |
| 2022-09-02 | Full name |
```

You can also use your GitHub name if you prefer.

**Comment by teeks99** [comment]
Done.

**Comment by Sesu8642** [comment]
Thanks!

**Pull request merged**
