### PR TITLE
Adapt pixthulu-ui skin and make ImageButton have a background

### PR DESCRIPTION
**Pull request by pserwylo**
See additional `README` in the skin directory. It explains how I've used SkinComposer to import the existing skin and then re-export after making changes. I realise you mentioned you would look into this alter, but it seemed relatively straightforward to hack on for this change. Hopefully this will allow incremental tweaks to the UI until you get around to overhauling the skin completely. Or you can use this for the base of your further plans to redo the skin.

The end result is that the dice button now looks like this:

 

**NOTE: This is a draft because it is built on #44. This also means the diff between this branch and `master` will look bigger until that is merged.**

### CODE REVIEW

**Comment by pserwylo** [comment]
I should say, that I find it particularly difficult to get the SkinComposer `.scmp` file to include relative paths. For my own games, I ended up giving up and just leaving a generic `/home/pete/code/GAME_NAME/skin/` path everywhere in the file, but I've tried my best to get it working with relative paths here. It may cause some issues when opening in SkinComposer for you, but hopefully you can see what the issue is if one arises and address it if need be.

**Comment by Sesu8642** [comment]
I got some errors when I opened the project in Skin Composer. Moving the font files into the resources directory seemed to help. Any reason to keep them outside that directory?

**Comment by Sesu8642** [comment]
Looks like I created come conflicts. I will deal with them.

**Comment by Sesu8642** [comment]
The image button looks really good btw!

**Pull request merged**
