### PR TITLE
Add adaptive icon

### LINKED ISSUE #53: Add adaptive/monochrome app icon for Android 13
For Android 13 apps can provide a monochrome launcher icon that can be used by launchers: https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

### PR DESCRIPTION
**Pull request by mueller-ma**
Closes #53

### CODE REVIEW

**Comment by mueller-ma** [comment]
The icon now has a white background. On my Android device the launcher added such a background to the current icon, so I didn't even notice it's not adaptive.

**Comment by Sesu8642** [comment]
Thanks! Could you add yourself to the [CLA](https://github.com/Sesu8642/FeudalTactics/blob/master/CLA.md), please?

**Comment by Sesu8642** [comment]
Tested on Android 13 (emulator) with theming and it looks very nice. Good job!
image

**Comment by Sesu8642** [comment]
I have a couple of questions, mostly for my understanding:
1. You moved the icons from drawable to mipmap because that's the correct place for icons and has basically been wrong before, right?
2. ic_launcher-playstore.png seems to be unused and is meant to be uploaded to the Play Store. Since I use /metadata/en-US/images/icon.png for that, could ic_launcher-playstore.png be removed?
3. What is the reason for the png files to have the round border/shadow baked in? To have the icon be consistent on new and older Android versions? In my emulated Android 7, most pre-installed apps don't have a background like this and Feudal Tactics looks a little out of place. Another disadvantage is that I would need to re-do the pngs if I ever decide to use a different backgound color which I might actually do at some point. I would at least like to have some gimp project file or something to be able to change it easily.

**Comment by mueller-ma** [comment]
1. Right, mipmap is the correct folder.
2. I pushed a commit to remove this file.
3. I created all icons with the Android Studio icon creator. It's not possible to create icons without a background there.

On Android 7 apps should provide a round icon (https://devblogs.microsoft.com/xamarin/round-launcher-icons-in-android-7-1/) so the background is required for this version. I could restore the old icons for Android 6 and lower. IMO the background looks good, though.

**Comment by Sesu8642** [comment]
Android 7.0 is the lowest supported anyway. Thanks!

**Pull request merged**
